### ISSUE TITLE
updates are not recognized on next tool-run

### ISSUE THREAD

**Issue by TobiasKoller** [h3xp/RickDangerousUpdate#50] opened 2022-10-19 09:19 UTC
The tool shows me all available updates.
But when I start them and leave for several hours the screensaver is active and when I run the tool again it has not updated the installed improvements.
I think it might happen when it failed to update an improvement (maybe of mega download-limits).
You should update the installed improvments right after each installation and not at the end (if this is the casee ;) )

**Comment by LizardWiz** [comment] 2022-10-19 14:12
This is done. Duplicate of #46, which is already in the v2.3.0 branch.

**Closed as completed by LizardWiz** 2022-10-19 14:12 UTC
