### ISSUE TITLE
Manual Genre Skip

### ISSUE THREAD

**Issue by LizardWiz** [h3xp/RickDangerousUpdate#60] opened 2022-11-04 13:54 UTC
Add skip button to manual genre mapping

**Comment by WolfRevo** [comment] 2022-11-04 14:08
More information:

Right now it forces you to choose a genre, or cancel all. Right now +START Pico8.sh is in a gamleist.xml file, and it is forcing you to put it into a collection (or you can't move forward). Hitting cancel, cancels out of the entire process by design (if you added 1,000 games and you don't want to finish you currently need to reboot).

Skip gives you the opportunity to skip a single entry and move forward.

**Comment by WolfRevo** [comment] 2022-11-06 16:19
Fixed and tested. Will be released with v.2.3.1

**Closed as completed by WolfRevo** 2022-11-06 16:19 UTC
Labels: enhancement
